#!/usr/bin/env bash
# Emscripten build of the SpeexDSP resampler (HQ sample-rate conversion for the
# worklet backend when the AudioContext cannot open the file's native rate).
#
#   scripts/build-resampler-wasm.sh    → public/speex-resampler.{js,wasm}
#
# Source: SpeexDSP 1.2.1 release tarball (BSD-3-Clause), pinned by SHA-256 and
# unpacked under .build/. Only libspeexdsp/resample.c is compiled; the ABI is
# src/resampler/speex_resampler_wasm.c. src/audio/resampler.ts falls back to
# linear interpolation when this module fails to load.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_DIR="$PROJECT_ROOT/public"
BUILD_DIR="$PROJECT_ROOT/.build/speexdsp"

SPEEXDSP_VERSION="1.2.1"
SPEEXDSP_URL="https://github.com/xiph/speexdsp/archive/refs/tags/SpeexDSP-${SPEEXDSP_VERSION}.tar.gz"
SPEEXDSP_SHA256="d17ca363654556a4ff1d02cc13d9eb1fc5a8642c90b40bd54ce266c3807b91a7"

PROJECT_ROOT="$PROJECT_ROOT" source "$SCRIPT_DIR/emsdk-env.sh"

mkdir -p "$BUILD_DIR" "$OUT_DIR"
TARBALL="$BUILD_DIR/speexdsp-${SPEEXDSP_VERSION}.tar.gz"
SRC_DIR="$BUILD_DIR/speexdsp-SpeexDSP-${SPEEXDSP_VERSION}"

if [ ! -f "$TARBALL" ]; then
  echo "Downloading $SPEEXDSP_URL"
  curl -fsSL -o "$TARBALL" "$SPEEXDSP_URL"
fi
echo "$SPEEXDSP_SHA256  $TARBALL" | sha256sum -c -
rm -rf "$SRC_DIR"
tar -xzf "$TARBALL" -C "$BUILD_DIR"

# Normally generated by configure.
cat > "$SRC_DIR/include/speex/speexdsp_config_types.h" <<'H'
#ifndef __SPEEX_TYPES_H__
#define __SPEEX_TYPES_H__
#include <stdint.h>
typedef int16_t spx_int16_t;
typedef uint16_t spx_uint16_t;
typedef int32_t spx_int32_t;
typedef uint32_t spx_uint32_t;
#endif
H

EXPORTS='["_rs_create","_rs_process","_rs_last_consumed","_rs_input_latency","_rs_reset","_rs_destroy","_malloc","_free"]'

echo "Compiling SpeexDSP resampler -> $OUT_DIR/speex-resampler.js"
emcc \
  "$SRC_DIR/libspeexdsp/resample.c" \
  "$PROJECT_ROOT/src/resampler/speex_resampler_wasm.c" \
  -I"$SRC_DIR/include" -I"$SRC_DIR/libspeexdsp" \
  -DFLOATING_POINT -DEXPORT= \
  -O3 -DNDEBUG \
  -s WASM=1 \
  -s EXPORTED_FUNCTIONS="$EXPORTS" \
  -s EXPORTED_RUNTIME_METHODS='["HEAPF32"]' \
  -s ALLOW_MEMORY_GROWTH=1 \
  -s INITIAL_MEMORY=4194304 \
  -s MODULARIZE=1 \
  -s EXPORT_NAME="createSpeexResamplerModule" \
  -s ENVIRONMENT="web,worker,node" \
  -o "$OUT_DIR/speex-resampler.js"
ls -lh "$OUT_DIR"/speex-resampler.*

"$SCRIPT_DIR/resampler-source-hash.sh" > "$OUT_DIR/resampler-source.sha256"
echo "Resampler WASM build finished."
