import { FlacDecoder } from './flacDecoder';
import { PlayerState } from './audioPlayer';

/*
 NOTE (diagnostic):
 - The SDL audio player relies on a modularized Emscripten module exposed by
   `createSdlAudioModule()` (see `sdl-audio.js` generated by Emscripten).
 - At runtime we expect the Module object to expose:
    - methods: _malloc, _free, _set_audio_data, _play, _pause_audio, ...
    - typed heap views or memory access point: `HEAPU8`, `HEAPF32`, `HEAP8`, or `wasmMemory`
 - Common failure modes observed in the console:
    - `Module.wasmMemory` / `Module.HEAPU8` are undefined (modularized exports differ)
    - `_malloc()` returns a pointer but accessing `Module.HEAP*` throws `RangeError`
    - `writeArrayToMemory` (used by `ccall`) fails with `offset is out of bounds` when heap views are stale
 - Troubleshooting checklist:
    - Build `sdl-audio.js` with ALLOW_MEMORY_GROWTH=1 so memory can grow if needed.
    - Ensure the generated module is MODULARIZE=1 and `createSdlAudioModule` returns the full runtime object.
    - At write time ALWAYS re-read `wasmMemory.buffer` or `Module.HEAPU8.buffer` (don't cache views at init).
    - Verify the C/C++ `_set_audio_data` expects number of samples vs number of bytes and pass the correct units.
    - Log `Object.keys(module)` and memory properties to validate what is available.
*/

// Define the Emscripten module interface
interface SdlModule {
  _init_audio(): number;
  _set_audio_data(dataPtr: number, length: number, channels: number, sampleRate: number): void;
  _play(): void;
  _pause_audio(): void;
  _resume_audio(): void;
  _stop(): void;
  _seek(time: number): void;
  _get_current_time(): number;
  _set_volume(volume: number): void;
  _cleanup(): void;
  _malloc(size: number): number;
  _free(ptr: number): void;
  HEAPF32: Float32Array;
  HEAPU8: Uint8Array;
  wasmMemory?: WebAssembly.Memory;
  HEAP8?: Int8Array;
  ccall(ident: string, returnType: string | null, argTypes: (string | null)[], args: (number | Float32Array | number[] | string[])[]): void;
} 

// Global function exposed by the WASM script
declare global {
  function createSdlAudioModule(): Promise<SdlModule>;
}

export class SdlAudioPlayer {
  private module: SdlModule | null = null;
  private isReady: boolean = false;
  private isPlaying: boolean = false;
  private duration: number = 0;
  private onStateChange?: (state: PlayerState) => void;
  private pollInterval: number | null = null;
  private lastVolume: number = 1.0;

  constructor() {
    this.initializeModule();
  }

  private async initializeModule() {
    // Load the ScriptProcessor->AudioWorklet shim first (best-effort). This enables environments
    // where ScriptProcessorNode is missing/deprecated to still work via AudioWorkletNode.
    if (!(window as unknown as { __sdl_script_processor_shim_loaded: boolean }).__sdl_script_processor_shim_loaded) {
      const shim = document.createElement('script');
      shim.src = 'script-processor-shim.js';
      shim.async = true;
      document.head.appendChild(shim);

      await new Promise<void>((resolve) => {
        shim.onload = () => { (window as unknown as { __sdl_script_processor_shim_loaded: boolean }).__sdl_script_processor_shim_loaded = true; resolve(); };
        shim.onerror = () => { console.warn('Script processor shim failed to load; continuing without shim.'); resolve(); };
      });
    }

    // Dynamically load the WASM/SDL script if not already present
    if (!window.createSdlAudioModule) {
      const script = document.createElement('script');
      script.src = 'sdl-audio.js';
      script.async = true;
      document.body.appendChild(script);

      await new Promise<void>((resolve, reject) => {
        script.onload = () => resolve();
        script.onerror = () => reject(new Error('Failed to load sdl-audio.js'));
      });
    }

    try {
      this.module = await window.createSdlAudioModule();

      // Diagnostics: helpful to print available exports and memory info to debug
      // runtime differences between build configurations (MODULARIZE/EXPORTS/wasm memory).
      console.debug('[SdlAudioPlayer] Module keys:', Object.keys(this.module || {}));
      console.debug('[SdlAudioPlayer] Module.wasmMemory:', this.module?.wasmMemory);
      console.debug('[SdlAudioPlayer] Module.HEAPU8:', (this.module as any)?.HEAPU8);

      const success = this.module._init_audio();
      if (!success) {
        console.error('Failed to initialize SDL audio');
      } else {
        this.isReady = true;
        this.startPolling();
      }
    } catch (err) {
      console.error('Error initializing SDL module:', err);
    }
  }

  setStateChangeCallback(callback: (state: PlayerState) => void): void {
    this.onStateChange = callback;
  }

  private notifyStateChange(): void {
    if (this.onStateChange) {
      this.onStateChange(this.getState());
    }
  }

  // Poll for playback position updates
  private startPolling() {
    if (this.pollInterval) window.clearInterval(this.pollInterval);
    this.pollInterval = window.setInterval(() => {
      if (this.isPlaying && this.module) {
        this.notifyStateChange();
      }
    }, 100);
  }

  async loadAudio(arrayBuffer: ArrayBuffer): Promise<void> {
    if (!this.module || !this.isReady) {
        // Retry init if not ready? or wait?
        // For simplicity, assume initialized by the time user clicks load.
        if (!this.module) throw new Error('SDL Module not initialized');
    }

    this.stop();
    this.notifyStateChange();

    try {
      const decoder = new FlacDecoder();
      const result = await decoder.decode(arrayBuffer);

      this.duration = result.duration;

      // Interleave samples
      const channels = result.channels;
      const length = result.samples[0].length;
      const interleavedLength = length * channels;
      const interleaved = new Float32Array(interleavedLength);

      for (let i = 0; i < length; i++) {
        for (let ch = 0; ch < channels; ch++) {
          interleaved[i * channels + ch] = result.samples[ch][i];
        }
      }

      // Allocate memory in WASM (in bytes) and write safely to the current WASM buffer
      const byteLength = interleaved.byteLength;
      const ptr = this.module._malloc(byteLength);

      if (!ptr || ptr === 0) {
        // Malloc failed: fall back to ccall copy (note: ccall -> writeArrayToMemory may hit RangeError if it writes into a stale view)
        console.warn('WASM malloc failed (returned 0). Trying ccall fallback that copies the array into WASM memory.');
        try {
          // Note: ccall/writeArrayToMemory requires Module.HEAPU8 to exist and be up-to-date.
          // If HEAPU8 is undefined or stale, this will throw "offset is out of bounds".
          this.module.ccall('set_audio_data', null, ['array', 'number', 'number', 'number'], [interleaved, interleavedLength, channels, result.sampleRate]);
        } catch (ccErr) {
          console.error('Fallback ccall set_audio_data failed:', ccErr);
          throw ccErr;
        }
      } else {
        try {
          // Important: _malloc may cause WebAssembly memory to grow. Never use a cached
          // Module.HEAP* view — re-read the underlying buffer each time it is needed.
          // Also confirm whether `_set_audio_data` expects the sample count or byte count:
          // - `interleavedLength` is currently number of float samples,
          // - `byteLength` is number of bytes (Float32Array.byteLength).
          // If `_set_audio_data` expects bytes, pass `byteLength` instead and update the C++ signature accordingly.

          let memoryBuffer: ArrayBufferLike;

          if (this.module.HEAPU8 && this.module.HEAPU8.buffer) {
            memoryBuffer = this.module.HEAPU8.buffer;
          } else if (this.module.wasmMemory && this.module.wasmMemory.buffer) {
            memoryBuffer = this.module.wasmMemory.buffer;
          } else if (this.module.HEAP8 && this.module.HEAP8.buffer) {
             memoryBuffer = this.module.HEAP8.buffer;
          } else {
             // Very likely cause: the module runtime doesn't expose the heap the way we expect
             // (different Emscripten config). Log available keys to help debugging and fail fast.
             console.error('[SdlAudioPlayer] Cannot find WASM memory buffer on module. Available keys:', Object.keys(this.module));
             throw new Error('Cannot find WASM memory buffer (HEAPU8, wasmMemory, or HEAP8 are missing)');
          }

          const destination = new Float32Array(memoryBuffer, ptr, interleavedLength);
          destination.set(interleaved);

          // Send to C++ (direct call, faster and avoids writeArrayToMemory)
          this.module._set_audio_data(ptr, interleavedLength, channels, result.sampleRate);
        } catch (err) {
          const heapByteLength = this.module.HEAPU8?.buffer?.byteLength ||
                                 this.module.wasmMemory?.buffer?.byteLength ||
                                 undefined;

          console.error('Failed to write audio data into WASM heap:', err, { ptr, byteLength, heapByteLength });

          // Try fallback ccall if direct write fails (covers browser-specific edge cases)
          try {
            this.module.ccall('set_audio_data', null, ['array', 'number', 'number', 'number'], [interleaved, interleavedLength, channels, result.sampleRate]);
          } catch (ccErr) {
            console.error('Fallback ccall set_audio_data also failed:', ccErr);
            // Free pointer and rethrow original error
            this.module._free && this.module._free(ptr);
            throw err;
          }
        } finally {
          // Free malloc'd memory (the C++ copy made its own copy into g_state.audioBuffer)
          this.module._free && this.module._free(ptr);
        }
      }

      this.notifyStateChange();

    } catch (error) {
      console.error('Error loading audio in SDL player:', error);
      throw error;
    }
  }

  play(): void {
    if (!this.module) return;
    this.module._play();
    this.isPlaying = true;
    this.notifyStateChange();
  }

  pause(): void {
    if (!this.module) return;
    this.module._pause_audio();
    this.isPlaying = false;
    this.notifyStateChange();
  }

  stop(): void {
    if (!this.module) return;
    this.module._stop();
    this.isPlaying = false;
    this.notifyStateChange();
  }

  seek(time: number): void {
    if (!this.module) return;
    this.module._seek(time);
    this.notifyStateChange();
  }

  getCurrentTime(): number {
    if (!this.module) return 0;
    return this.module._get_current_time();
  }

  getDuration(): number {
    return this.duration;
  }

  getState(): PlayerState {
    return {
      isPlaying: this.isPlaying,
      currentTime: this.getCurrentTime(),
      duration: this.getDuration(),
      isLoading: false
    };
  }

  setVolume(volume: number): void {
    this.lastVolume = volume;
    if (this.module) {
      this.module._set_volume(volume);
    }
  }

  getAnalyser(): AnalyserNode {
    // SDL player doesn't support Web Audio AnalyserNode integration yet
    // Return a dummy analyser to satisfy interface if needed, or throw/return null and handle in UI
    // The UI handles null but the type signature says AnalyserNode.
    // We'll cast null or create a dummy one.
    // Creating a dummy one requires AudioContext.
    const ctx = new AudioContext();
    const analyser = ctx.createAnalyser();
    return analyser;
  }

  destroy(): void {
    this.stop();
    if (this.pollInterval) clearInterval(this.pollInterval);
    if (this.module) {
      this.module._cleanup();
    }
  }
}
